version: '3.4'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: minhasenhasecreta
      POSTGRES_DB: registration
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    links:
      - postgres
    depends_on:
      - postgres
    restart: always
    ports:
      - 8081:8080

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  notification:
    image: registration-app
    container_name: registration-ap
    restart: on-failure
    build: .
    environment:
      TZ: GMT
    ports:
      - "9003:8080"
    networks:
      - backend
    depends_on:
      - postgres
    links:
      - "postgres:database"

volumes:
  db-data:

networks:
  backend: