version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  notification:
    container_name: notification
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    depends_on:
      - rabbitmqwq